### ISSUE TITLE
Dagster `perform_mongo_updates` op fails with `TypeError`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#631]
A bug was introduced in commit https://github.com/microbiomedata/nmdc-runtime/pull/620 that is leading to Dagster reporting the following error when the `perform_mongo_updates` op runs.

```py
TypeError: _add_schema_docs_with_or_without_replacement() missing 2 required positional arguments: 'mongo' and 'docs'
```

This was originally reported by @pkalita-lbl [here](https://nmdc-group.slack.com/archives/C0739GREU9G/p1723222294109459).

I think the error stems from line 531 in `nmdc_runtime/site/ops.py` lacking the two arguments that the function being called normally tries to use.

https://github.com/microbiomedata/nmdc-runtime/blob/3fd7786ffcc680eaf2b1fdd677e5201912208b7d/nmdc_runtime/site/ops.py#L531

https://github.com/microbiomedata/nmdc-runtime/blob/3fd7786ffcc680eaf2b1fdd677e5201912208b7d/nmdc_runtime/site/ops.py#L541-L543

Based upon the surrounding code, I suspect the fix will look like this.

```diff
-     add_docs_result = _add_schema_docs_with_or_without_replacement()
+     add_docs_result = _add_schema_docs_with_or_without_replacement(mongo, docs)
```

CC: @aclum

**Comment by dwinston** [comment]
Oy. I will fix and add test coverage for the body of `perform_mongo_updates`.
